name: nginx-python

on:
  push:
    branches:
      - '*'

jobs:
  # Build and push the Docker image
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # login to Docker Hub using the secrets provided
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          context: .
          file: ./Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-python:latest
          # tags: latest
